FROM node:24.13.1-alpine3.22 AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.29.1-alpine3.22
COPY --from=build /app/dist /srv
COPY installation/frontend/nginx.conf /etc/nginx/conf.d/default.conf
