server {
    listen 8080;
    server_name _;

    root /srv;
    index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }

  location = /sw.js {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }
}
